{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "app.serviceAccountName" . }}
  namespace: develop
  labels:
{{ include "app.labels" . | indent 4 }}
{{- end -}}
